### ISSUE TITLE
add pyopenms logo to website and pyopenms documentation

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-website#104]
I initially failed but probably just requires some CSS editing.
Maybe also ask @rahul
https://github.com/OpenMS/OpenMS-website/pull/102

**Comment by jpfeuffer** [comment]
I think the first step is to revert all the theme customizations and just put the overwritten files in our repository.

**Comment by timosachsenberg** [comment]
does this need to be done for the whole theme or is this single css enough?

**Comment by jpfeuffer** [comment]
please please do it for the whole theme

**Comment by jpfeuffer** [comment]
you will never be able to pull theme updates/fixes without rebasing etc.

**Comment by matteopilz** [comment]
Should we actually keep our own fork of the theme or use the main repo instead? https://github.com/scientific-python/scientific-python-hugo-theme

**Comment by jpfeuffer** [comment]
no, correct, only use the main repo

**Comment by jpfeuffer** [comment]
then just place the files that were changed at the exact same locations in our OpenMS-website repo and hugo's template ordering process will automatically pick up our versions.

**Comment by jpfeuffer** [comment]
Do a quick compare on github.com to see all the changes from rahul. should only be 4-5 files IIRC

**Comment by jpfeuffer** [comment]
Fixed for website in #105 

Please open an issue for documentation on the docs page.
