### ISSUE TITLE
Relink developer docs

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS-website#118]
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/tutorial.html

**Comment by matteopilz** [comment]
Shouldn't this rather be accessible from the OpenMS docs than the website?

**Comment by matteopilz** [comment]
https://github.com/OpenMS/OpenMS-docs/pull/212

**Comment by enetz** [comment]
should be fixed in https://github.com/OpenMS/OpenMS/issues/7104 and https://github.com/OpenMS/OpenMS/pull/7109
