### ISSUE TITLE
Show and highlight web apps on OpenMS website

### ISSUE THREAD

**Issue by matteopilz** [OpenMS/OpenMS-website#136]
We generate our website with gohugo. Hugo will in general convert markdown .md and restructured text .rst files into html. For custom styling we still need html code sections, which are in our partials folder: https://github.com/OpenMS/OpenMS-website/tree/main/layouts/partials

We would need some nice way to present our web apps on the website, with mainly a name and some kind of logo. We can also remove the overview of proteomics, metabolomics and workflows, which gets its structrur from hero items in the partials folder. I would recommend looking at examples from different website that also use gohugo how to create a html partial https://gohugo.io/showcase/. Because we want to add more apps in time, we probably need some scroll or search function for the apps.

We can also make use of the hero item partial and change it.

**Comment by JKVISION1101** [comment]
@matteopilz 

I opened pull request. Please let me know if there's anything to fix.
