### ISSUE TITLE
Applications not very maintainable

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-website#25]
I don't like that we have to maintain an excerpt and the full markdown for every application.
Can't the excerpt be extracted? E.g. we make sure the first section of each application is a short description?

**Comment by jpfeuffer** [comment]
Yes, this is the problem. You have applications.md and then another MD for every application. This is a huge duplication.

Use this: https://gohugo.io/content-management/summaries/

**Comment by rahul799** [comment]
@jpfeuffer the link I posted above is summary page only that is auto generated. **applications.md** is pointing to a slightly different url https://openms.github.io/applications/ .

**Comment by jpfeuffer** [comment]
Aaah ok that was confusing.
Yes this is not bad! How is this done? Can you point me to the code that does that?

**Comment by jpfeuffer** [comment]
@rahul799

**Comment by jpfeuffer** [comment]
How can we change how it renders it?
We still need the Sidebar, we want to add a read more button.

**Comment by rahul799** [comment]
It gets rendered while starting the server. For adding sidebar or read more button, I will have to make changes in the [theme](https://github.com/OpenMS/scientific-python-hugo-theme/blob/main/layouts/partials/section/section.html#L29).

**Comment by jpfeuffer** [comment]
But shouldn't this already have a sidebar? https://github.com/OpenMS/scientific-python-hugo-theme/blob/main/layouts/partials/section/section.html#L3

**Comment by jpfeuffer** [comment]
How do we know, which template applies to which md file/folder?

**Comment by rahul799** [comment]
So actually the sidebar is rendered when we have atleast one heading of the level h1,h2 or h3 in the md file. In case of the summary page, all the headings are controlled using font-size. So if we want the sidebar, a small alteration is needed
and that will do the job.

<img width="1233" alt="Screenshot 2022-07-14 at 10 00 19 PM" src="https://user-images.githubusercontent.com/41531498/179031787-794301d1-81f9-446d-b197-84a9809bf24f.png">

**Comment by rahul799** [comment]
> How do we know, which template applies to which md file/folder?

Is it fine if I explain it in the doc?

**Comment by jpfeuffer** [comment]
Yes, yes. :+1:

**Comment by rahul799** [comment]
So should we replace https://openms.github.io/applications/ page with the above one?

**Comment by jpfeuffer** [comment]
I would say so. We should adapt the summaries of the pages with the <-- read more --> tag but otherwise, this solution is much better.
