### ISSUE TITLE
Some links on main page linking to wrong sections

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-website#53]
e.g., create workflows links to pyOpenMS.
probably others as well

**Comment by jpfeuffer** [comment]
Still major issue

**Comment by jpfeuffer** [comment]
@rahul799 Still major issue, also related to #59

**Comment by rahul799** [comment]
Sorry for the delay @jpfeuffer . I am facing some issues with my laptop due to which I am not able to work. I will fix it as soon as possible.

**Comment by rahul799** [comment]
Hey @jpfeuffer,
I have updated the links.

**Comment by enetz** [comment]
Should be fixed. I will close for now.

**Comment by timosachsenberg** [comment]
Thanks
