### ISSUE TITLE
How to do permanent redirects on the new website?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-website#58]
In wordpress we had regex redirects, e.g.:

`www.openms.de/documentation/*` redirects to `abibuilder.cs.uni-tuebingen.de/archive/Documentation*`

We must keep these redirects alive, so we need to find a solution for that.

**Comment by jpfeuffer** [comment]
The easiest way is probably to use netlify for hosting. GH pages does not support it.
Otherwise, we need to use static HTML or JS for every possible redirect.

**Comment by rahul799** [comment]
Yeah. I will also vote for netlify. Do we have any account where I can deploy it?

**Comment by jpfeuffer** [comment]
Not yet, I think we have to discuss that in a meeting. Do you think the free tier will be enough for us?
Would we do the builds on netlify?

**Comment by rahul799** [comment]
Yes. I think free tier will be fine. Yes netlify has direct integrations with GitHub so we can use it for build.

**Comment by timosachsenberg** [comment]
are there some missing? e.g., https://www.openms.de/current_doxygen/html/index.html

**Comment by jpfeuffer** [comment]
The added redirects are wrong, as commented.

**Comment by jpfeuffer** [comment]
ping ping ping
Issue number 4 related to this
