### ISSUE TITLE
General remarks

### ISSUE THREAD

**Issue by matteopilz** [OpenMS/OpenMS-website#60]
I have looked through (most of) our website and found some things that should be changed. Some of it is my opinion, meaning we should discuss this first in a meeting.

### [Main Page](https://openms.github.io/)
**What is OpenMS** ?
- [ ] Code of Conduct link missing.

**“Advanced users can use OpenMS to”** 
- [x] “Analyze large datasets” link leads to OpenMS on Galaxy but has a logo for nf-core.

**Quick facts for Users...**
- [ ] (Opinion) Summary OpenMS leads to GitHub, pyOpenMS to https://pypi.org/project/pyopenms/, maybe they should both lead to their respective documentation pages, add separate button for OpenMS GitHub
- [ ] “Supported Workflows:” links: Knime & Galaxy start at the section paragraph, Nextflow at the section header.
- [ ] Supported Platforms: blocks decrease in size from Windows over Linux to Mac.

**Footer**
- [x] “Get help” should be “Help”.

### [Press Kit](https://openms.github.io/press-kit/)
- [ ] (Opinion) This could go to ["Citing OpenMS".](https://openms.github.io/citing-openms/)

### [Installation Instructions](https://openms.github.io/install/#installation-instructions)
**GENERAL**  
- [ ] Build from source is missing.
- [x] Language sometimes too casual: “It is most easily installed” or incorrect: “you will get an error advising you this when executing a tool”
- [x] Some section headers have arrows and some don’t.
- [x] (Opinion) Remove smileys, this could also go for all pages
- [x] (Opinion) Installing OpenMS in KNIME should not be a separate section than “Installation of OpenMS in Galaxy or NextFlow”. Either make all three separate or make one workflow installation section.
- [x] In the opening dialog fill in at least one of the following additional Update Sites (if not already present): --> missing sites

**Installation of pyOpenMS**
- [x] Section not registered in table of content on the left
- [x] Note: wrong section
- [x] pyOpenMS webpage link should be included
- [ ] (Opinion) pyOpenMS list supported python versions.

**Python and OpenMS installation guide**
- [x]  (Opinion) A second pyOpenMS section? Information should be shortened and put together with prior section

**Installation of OpenMS binaries**
- [x] Once the path is exported, close the current terminal and open a new one. - why? The tutorial ends here, so either remove the sentence or change it to something like "to use the tools close the current terminal and open a new one."

**Installation of OpenMS in Galaxy or NextFlow**
- [x]  (Opinion) Not really an installation, maybe change this to "Use OpenMS in Galaxy or NextFlow". This should then also be adapted in the section.

### [Training](https://openms.github.io/training/)
- [x]  (Opinion) Remove training page, move training events to either a new page, "Community" or "About us". Tutorials should go to https://openms.github.io/tutorials/ which should get a "Tutorials" entry in the navigation bar.

### [Training Events](https://openms.github.io/training-events/#openms-training-events)
- [x] (Opinion) Distinction between recent and older events necessary? This is already implied when scrolling down.
- [x] (Opinion) Registrations should be removed.

### [Community](https://openms.github.io/community/)
- [x] (Opinion) Site should be better structured: Where should I go with what background/intention (should be clear from the section titles)? Alternative would be to make it alphabetical.
- [x] GitHub issue tracker items, link directly to labeled issues, e.g. https://github.com/OpenMS/OpenMS/labels/bug?

**OpenMS Mailing List**
- [x] “This list is the main” --> “These lists are the main” / “Our mailing lists are the main”

**Join the OpenMS community**
- [x] "openms" to "OpenMS"

### [About Us](https://openms.github.io/about/)
**Some information about the OpenMS project and community**
- [x] OpenMS is **a** free software
- [x] BSD clause mentioned twice

**Executive Committee**
- [ ] (Opinion) Section necessary on our website?

### [Teams](https://openms.github.io/teams/)
- [ ] Docs team three times?
- [ ] (Opinion) Maybe make a list format to prevent multiple mentions.
- [ ] (Opinion) Governance necessary?

### [Publications](https://openms.github.io/publications/)
- [x] (Opinion) Links to the publications would be nice to have.

### Additional
- [ ] Page titles (text shown in browsers from open tab or bookmark) are all identical "openms".

**Comment by matteopilz** [comment]
h1 headers need to be included in the sidebar with the restructure of the installation page.

**Comment by jpfeuffer** [comment]
Also, pyopenms install is not 100% correct. The package is in the bioconda channel. You need conda-forge only for parts of the dependencies.

**Comment by cbielow** [comment]
the installation instructions, e.g. for Windows
https://www.openms.de/install/#installation-on-windows
say `simply download and execute the installer from OpenMS.de `. Very funny. The user is on that very page...

The readthedocs install instructions (which are somewhat identical?), provide a link.
https://openms.readthedocs.io/en/latest/installations/installation-on-windows.html

So:
1) why duplicate information, i.e. make it harder maintain
2) please make sure download links are present

**Comment by timosachsenberg** [comment]
what is the current state of this blocker  now that the PR was merged?

**Comment by matteopilz** [comment]
I would say there is nothing important left on the website, as most of the topics from the remaining issues have been moved to the docs. The layout of the https://openms.de/contributors/ page is a bit strange with docs team three times, but that is relatively minor.

**Comment by timosachsenberg** [comment]
yep that is true... think these should be merged
