### ISSUE TITLE
add summary on Dev meeting

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-website#86]

**Comment by enetz** [comment]
This is supposed to be a summary / update on the last dev meeting specifically, in `News`, right?
Should we also add a page about these meetings in general under `Community`?

**Comment by timosachsenberg** [comment]
hmm I think a news item is sufficient for now.

**Comment by timosachsenberg** [comment]
state?

**Comment by enetz** [comment]
If the text in that PR is fine and can be merged, this is done.

**Comment by timosachsenberg** [comment]
great! thanks
